# Info
wb_project: 'miccai_dev'
wb_sweepname: 'bens_trials_10'
# Sweep type
sweep_method: 'random'
sweep_goal: 'minimize'
sweep_metric_name: 'validation_loss'
sweep_count: 3
# Hyperparams (formatted)
# Still need to specify the dataset frac split to use...
batch_size: 4
# lr: {'max': 0.0001, 'min': 0.00000001, 'distribution': 'log_uniform'}
lr: 0.00003
grad_clip_val: 1.0
augmentations: '/home/kindersc/repos/example_repo/segmentation_generic/yamls/augmentations/medsam/medium_augs.yaml'
patience: 10
max_epochs: 2
# early_stopping_monitor: {'values': ['val_loss']}
early_stopping_monitor: 'val_loss'
# optimizer_name: {'values': ['adam', 'adamw']}
optimizer_name: 'adam'
# scheduler_name: {'values': ['exponential_decay', 'cosine_annealing', 'cyclic_lr', 'none']}
scheduler_name: 'exponential_decay'
adamw_weight_decay: 0.0001
sgd_momentum: 0
log_every_n_steps: 10
# Frac num
frac_num: 10