# Info
wb_project: 'scott-ga-medsam-sweep'
wb_sweepname: 'sweep_hyperparams_first'
# Sweep type
sweep_method: 'random'
sweep_goal: 'minimize'
sweep_metric_name: 'validation_loss'
sweep_count: 50
# Hyperparams (formatted)
batch_size: {'values': [8, 16, 24, 32, 40, 48, 56, 64, 72, 80]}
lr: {'max': 0.00007, 'min': 0.000005, 'distribution': 'log_uniform'}
grad_clip_val: {'max': 3.0, 'min': 0.01, 'distribution': 'uniform'}
augmentations: {
  'values': [
    '/home/kindersc/repos/segmentation_generic/yamls/augmentations/medsam/low_augs.yaml',
    '/home/kindersc/repos/segmentation_generic/yamls/augmentations/medsam/medium_augs.yaml',
    '/home/kindersc/repos/segmentation_generic/yamls/augmentations/medsam/high_augs.yaml'
  ]
}
patience: {'values': [10]}
max_epochs: {'values': [500]}
early_stopping_monitor: {'values': ['val_loss']}
optimizer_name: {'values': ['adam', 'adamw']}
scheduler_name: {'values': ['exponential_decay', 'cosine_annealing', 'cyclic_lr', 'none']}
adamw_weight_decay: {'max': 0.01, 'min': 0.0000001, 'distribution': 'log_uniform'}
sgd_momentum: {'max': 0.99, 'min': 0.01, 'distribution': 'log_uniform'}
log_every_n_steps: {'values': [10]}